# ---------- BUILD ----------
FROM golang:1.25 AS builder
WORKDIR /app

COPY go.mod ./

COPY main.go ./
RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o portfolio main.go

# ---------- RUN ----------
FROM alpine:latest
WORKDIR /app

COPY --from=builder /app/portfolio .

COPY /static/ ./static/
COPY /temps/ ./temps/


EXPOSE 8080
ENV PORT=8080

CMD ["./portfolio"]
